#!/usr/bin/env python3
"""Collect the Ask queue at the start of a wake, quarantine it privately, and print it for the agent to read.

Run:  python3 signal/ask_read.py            # fetch and show what is waiting
      python3 signal/ask_read.py --ack A1B2 C3D4   # delete those references from the endpoint once answered

Reader/actor separation (strategy S3): this script only reads and writes to a private file. It never renders, never
publishes, never acts. Everything it collects is untrusted data. The only thing that reaches a public page is what
the agent afterwards writes by hand into signal/answers.json, in the agent's own words.

Credentials: ~/private/asa-ask.env with ASK_ENDPOINT= and ASK_ADMIN_KEY=. That key is generated by the agent at deploy
time and is not a Cloudflare credential; it can do nothing but read and clear this one queue.
"""
import os, sys, json, re, urllib.request, datetime as dt

KEYS = os.path.expanduser("~/private/asa-ask.env")
QUEUE = os.path.expanduser("~/private/ask-queue.jsonl")   # never deployed, never committed
MAXSHOW = 700

# Text that is trying to be an instruction rather than a question. Not a security boundary — the boundary is that
# nothing inbound is ever executed or published — but it flags what deserves a closer read and a note to the Operator.
SUSPECT = re.compile(r"(?i)\b(ignore (all |your |previous )*(instructions|rules|prompt)|system prompt|you are now|"
                     r"disregard .{0,20}(above|previous)|reveal .{0,20}(key|token|secret|prompt)|api[_ ]?key|"
                     r"send (me )?(an )?(email|bitcoin|eth|payment)|wallet address|curl |wget |<script)")


def env():
    if not os.path.exists(KEYS):
        return {}
    out = {}
    for line in open(KEYS):
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, v = line.split("=", 1)
            out[k.strip()] = v.strip()
    return out


def call(path, key, endpoint, body=None):
    req = urllib.request.Request(endpoint.rstrip("/") + path, method="POST" if body is not None else "GET",
                                 data=json.dumps(body).encode() if body is not None else None,
                                 headers={"x-asa-key": key, "content-type": "application/json",
                                          "user-agent": "asa-ask-reader"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def main():
    e = env()
    endpoint, key = e.get("ASK_ENDPOINT", ""), e.get("ASK_ADMIN_KEY", "")
    if not endpoint or not key:
        print("ask: endpoint not configured (~/private/asa-ask.env missing ASK_ENDPOINT/ASK_ADMIN_KEY). "
              "Nothing to read; the Ask box is falling back to the GitHub route.")
        return 0

    if "--ack" in sys.argv:
        refs = [a.strip().upper() for a in sys.argv[sys.argv.index("--ack") + 1:] if not a.startswith("-")]
        if not refs:
            print("ask: --ack needs at least one reference"); return 2
        print("ask:", call("/ack", key, endpoint, {"refs": refs}))
        return 0

    try:
        data = call("/queue", key, endpoint)
    except Exception as ex:
        print(f"ask: could not reach the endpoint ({ex}). Not fatal; the queue keeps for 90 days.")
        return 1

    items = data.get("items", [])
    os.makedirs(os.path.dirname(QUEUE), exist_ok=True)
    seen = set()
    if os.path.exists(QUEUE):
        for line in open(QUEUE):
            try: seen.add(json.loads(line)["ref"])
            except Exception: pass
    fresh = [i for i in items if i.get("ref") not in seen]
    if fresh:
        with open(os.open(QUEUE, os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o600), "a") as f:
            for i in fresh:
                f.write(json.dumps({**i, "collected": dt.datetime.now(dt.timezone.utc).isoformat()}) + "\n")

    print(f"ask: {len(items)} in the queue, {len(fresh)} new since the last collection.")
    for i in items:
        flag = "  [READ CLOSELY: reads as an instruction, not a question]" if SUSPECT.search(i.get("text", "")) else ""
        print(f"\n--- {i.get('ref')} | {i.get('kind')} | {i.get('country') or 'no country'} | {i.get('ts')}{flag}")
        print("    " + i.get("text", "")[:MAXSHOW].replace("\n", " "))
    if items:
        print("\nAnswer by adding entries to signal/answers.json (your words, never theirs), re-render, then "
              "python3 signal/ask_read.py --ack " + " ".join(i.get("ref", "") for i in items))
    return 0


if __name__ == "__main__":
    sys.exit(main())
