/*
 * asa-ask — the endpoint behind the Ask box on pacificaidsignal.org.
 *
 * Runs as a Cloudflare Worker on the Operator's account. It is deliberately the whole of the public attack surface:
 * the agent's own server is never exposed, and this script can do exactly three things — accept a short message,
 * hand back a reference code, and let the agent collect the queue with a key the agent generated itself.
 *
 * What it stores: the message text, the kind, the country slug, the timestamp, the reference. That is all.
 * What it does not store: IP addresses, user agents, cookies, names, e-mail addresses, referrers, any identifier
 * of the sender. Rate limiting uses a salted hash of the IP that is never written next to a message and expires
 * within the hour. There is no analytics of any kind.
 *
 * Bindings required:  KV namespace ASKS        (create once)
 * Secrets required:   ADMIN_KEY                (random, generated by the agent, used only on /queue and /ack)
 *                     SALT                     (random, used only for the rate-limit hash)
 */

const ORIGINS = ["https://pacificaidsignal.org", "https://www.pacificaidsignal.org", "https://intexpagent-01.github.io"];
const KINDS = ["question", "watch", "feedback"];
const MAXLEN = 700;
const PER_HOUR = 6;            // messages per IP per hour
const REF_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";   // no I/L/O/0/1: these get read aloud and typed

function cors(origin) {
  const allow = ORIGINS.includes(origin) ? origin : ORIGINS[0];
  return { "access-control-allow-origin": allow, "access-control-allow-methods": "POST, OPTIONS",
           "access-control-allow-headers": "content-type", "access-control-max-age": "86400", "vary": "origin" };
}
function json(obj, status, extra) {
  return new Response(JSON.stringify(obj), { status: status || 200,
    headers: Object.assign({ "content-type": "application/json; charset=utf-8", "cache-control": "no-store" }, extra || {}) });
}
async function hash(s) {
  const d = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(s));
  return [...new Uint8Array(d)].slice(0, 12).map(b => b.toString(16).padStart(2, "0")).join("");
}
function ref() {
  const a = new Uint8Array(5); crypto.getRandomValues(a);
  return [...a].map(b => REF_ALPHABET[b % REF_ALPHABET.length]).join("");
}
/* Printable characters only, collapsed whitespace, capped. Anything outside this never reaches storage. */
function clean(s) {
  return String(s == null ? "" : s)
    .replace(/[\u0000-\u001f\u007f-\u009f\u200b-\u200f\u2028\u2029\u202a-\u202e\ufeff]/g, " ")
    .replace(/\s+/g, " ").trim().slice(0, MAXLEN);
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const origin = request.headers.get("origin") || "";

    if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: cors(origin) });

    /* --- the agent collecting its queue. Key is a secret the agent generated; it is not a Cloudflare credential. --- */
    if (url.pathname === "/queue" || url.pathname === "/ack") {
      const key = request.headers.get("x-asa-key") || url.searchParams.get("k") || "";
      if (!env.ADMIN_KEY || key !== env.ADMIN_KEY) return json({ error: "no" }, 403);
      if (url.pathname === "/queue") {
        const list = await env.ASKS.list({ prefix: "q:", limit: 200 });
        const out = [];
        for (const k of list.keys) {
          const v = await env.ASKS.get(k.name);
          if (v) out.push(JSON.parse(v));
        }
        return json({ count: out.length, items: out });
      }
      const body = await request.json().catch(() => ({}));
      const refs = Array.isArray(body.refs) ? body.refs.slice(0, 200) : [];
      const list = await env.ASKS.list({ prefix: "q:", limit: 200 });
      let n = 0;
      for (const r of refs) {
        for (const k of list.keys) if (k.name.endsWith(":" + r)) { await env.ASKS.delete(k.name); n++; }
      }
      return json({ deleted: n });
    }

    if (request.method !== "POST") {
      return new Response("asa-ask. POST {text, kind, country} from pacificaidsignal.org.\n",
        { status: 405, headers: { "content-type": "text/plain" } });
    }
    if (origin && !ORIGINS.includes(origin)) return json({ error: "Wrong origin." }, 403, cors(origin));

    const body = await request.json().catch(() => null);
    if (!body) return json({ error: "Send JSON." }, 400, cors(origin));

    const text = clean(body.text);
    if (text.length < 3) return json({ error: "A few more words, please." }, 400, cors(origin));
    const kind = KINDS.includes(body.kind) ? body.kind : "question";
    const country = clean(body.country).toLowerCase().replace(/[^a-z-]/g, "").slice(0, 40);

    const ip = request.headers.get("cf-connecting-ip") || "0";
    const bucket = "rl:" + (await hash(ip + "|" + (env.SALT || "") + "|" + Math.floor(Date.now() / 3600000)));
    const seen = parseInt((await env.ASKS.get(bucket)) || "0", 10);
    if (seen >= PER_HOUR) {
      return json({ error: "That is enough for one hour. Everything you sent is already in the queue." }, 429, cors(origin));
    }
    await env.ASKS.put(bucket, String(seen + 1), { expirationTtl: 3900 });

    const r = ref();
    const record = { ref: r, ts: new Date().toISOString(), kind, country, text };
    /* 90 days: long enough that a queue the agent cannot reach for a week loses nothing, short enough not to hoard. */
    await env.ASKS.put("q:" + record.ts + ":" + r, JSON.stringify(record), { expirationTtl: 7776000 });
    return json({ ref: r }, 200, cors(origin));
  }
};
